### ISSUE TITLE
why not send CONNECT_REQ to periph

### ISSUE THREAD

**Issue by amigomcu** [bluetoother/ble-shepherd#10]
hi all,
i run the demo program (sensorTagApp.js) with my custom device.
but it don't join with network .
Discovered event is trigger and return true , it should be Set up link,
have any advance for it ?

HW.cc2540 usb dongle.
FW.Host Test

periph info:
nordic_blinky adv :
http://imageshack.com/i/pnMFDpBrp
nordic_blinky service:
http://imageshack.com/i/pnpzVKqDp

var Q = require('q'),
    _ = require('lodash');

var BShepherd = require('../index'),
    path = '/dev/ttyACM0',
    options = {
        baudRate: 115200,
        rtscts: true,
        flowControl: true
    };

var central = new BShepherd('cc-bnp', path, options);
// var central = new BShepherd('noble');
var keyFobPlg = require('bshep-plugin-ti-keyfob');

var discoveredHdlr = function (peripheralInfo) {
	console.log('discover addr:'+peripheralInfo.addr);
return true;
}

central.support('Nordic_Blinkly', keyFobPlg);

central.start();
central.onDiscovered(discoveredHdlr);

central.on('ready', function () {
    console.log('ready to permitjoin');
    central.permitJoin(60);
});

central.on('ind', function(msg) {
    var periph = msg.periph;
    
    switch (msg.type) {
        case 'devStatus':
            break;
        case 'devIncoming':
            if (periph.name === 'sensorTag') {
                console.log('Sensor Tag join the network');
            } else if (periph.name === 'keyFob') {
                console.log('KeyFob join the network');
            }
            break;
        case 'devLeaving':
            break;
        case 'attNotify':
            break;
        case 'attChange':
            break;
        case 'devNeedPasskey':
            break;
    }
});

central.on('error', function (err) {
    console.log(err);
});

central.on('permitJoining', function (timeLeft) {
        console.log(timeLeft);
});

//bshep-plugin-ti-keyfob, always return true, don't check the uuid 
    examine: function (periph, basicInfo) {
        var isMine  = false,
            checkServList = [ '0x1802', '0x1803', '0x1804', '0x180f', '0xffa0', '0xffe0' ],
            count = 0;

        if (basicInfo.devName === 'Nordic_Blinky' ) {
            for(var hdl in periph.servs) {
                for(var i = 0; i < checkServList.length; i += 1)
                    if (periph.servs[hdl].uuid === checkServList[i]) count += 1;
            }

            //if (count === 6)
            isMine  = true;
        }

        return true;//always true
    }

**Comment by hedywings** [comment]
Hello @amigomcu, in the latest version of ble-shepherd (v1.1.5), the [onDiscovered()](https://github.com/bluetoother/ble-shepherd/wiki#API_onDiscovered) API has been modified, so your discoveredHdlr() should like the following code:

```js
var discoveredHdlr = function (peripheralInfo, callback) {
    console.log('discover addr:'+peripheralInfo.addr);

    setImmediate(function () {
        callback(null, true);
    });
};
```

Please try again, and if there is still problem, also please let me know, thank you!

**Comment by amigomcu** [comment]
hi hedywings,
Thank you for considering my request.

now ,i try to add  setImmediate at discoveredHdlr follow,
it also not send connect_req with peripheral.


var discoveredHdlr = function (peripheralInfo, callback) {
    console.log('discover addr:'+peripheralInfo.addr);
    if(	peripheralInfo.addr == 0xe6025660c82b) {
	    console.log('try to connect');
	    setImmediate(function () {
        	callback(null, true);
    	});
    else
         return false;
    }
};

Debug Messages
^Cuser@ubuntu:~/ble-shepherd/examples$ sudo DEBUG=ble-shepherd* node sensorTagApjsj
  ble-shepherd:init BLE Central init done! Wait for BLE network establishment +0ms
  ble-shepherd:init Central address: 0xd03972b39305 +2ms
  ble-shepherd:init BLE establishing stage 1: setting network parameters +2ms
  ble-shepherd:init BLE establishing stage 2: loading peripherals from database. +39ms
  ble-shepherd:init BLE establishing stage 3: asynchrnously connect devices in database. +3ms
  ble-shepherd:init BLE network establishing done! +0ms
  ble-shepherd:evtLsns peripheral 0xe6025660c82b discovered +2s
discover addr:0xe6025660c82b
try to connect
  ble-shepherd:evtLsns peripheral 0xe6025660c82b discovered +4s
discover addr:0xe6025660c82b
try to connect
  ble-shepherd:evtLsns peripheral 0xe6025660c82b discovered +4s
discover addr:0xe6025660c82b
try to connect

**Comment by amigomcu** [comment]
update the cc-bnp ,example info msg and nodejs/npm version,

user@ubuntu:~/cc-bnp/examples$ node -v
v6.10.1
user@ubuntu:~/cc-bnp/examples$ npm -v
3.10.10

user@ubuntu:~/cc-bnp/examples$ sudo node ble_connect.js 
{ GenericError(17): bleAlreadyInRequestedMode
    at new GenericError (/home/user/cc-bnp/lib/hci/ccBnpError.js:43:12)
    at BleHci.<anonymous> (/home/user/cc-bnp/lib/hci/bleHci.js:350:29)
    at emitOne (events.js:96:13)
    at BleHci.emit (events.js:188:7)
    at /home/user/cc-bnp/lib/hci/bleHci.js:316:16
    at _fulfilled (/home/user/cc-bnp/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/user/cc-bnp/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/user/cc-bnp/node_modules/q/q.js:816:13)
    at /home/user/cc-bnp/node_modules/q/q.js:570:49
    at runSingle (/home/user/cc-bnp/node_modules/q/q.js:137:13)
  name: 'GenericError(17)',
  type: 'GenericError',
  message: 'bleAlreadyInRequestedMode',
  errorCode: 17,
  isCcBnpError: true }

**Comment by amigomcu** [comment]
hi ,
now i try another peripheral , it do connect_request with it.
that see the ble-shepherd that can't see some adv data info.
should be the adv address type(random type).
http://i.imgur.com/Zutd34b.png

see follow
1. ble-shepherd successs
http://i.imgur.com/ET50hTJ.png
http://i.imgur.com/APD7wcJ.png

2.ble-shepherd failed
http://imageshack.com/i/pnMFDpBrp

I will be grateful for any help you can provide.

**Comment by hedywings** [comment]
Hi @amigomcu, 

Could you add some console.log() command to [ccbnpDrivers.connect](https://github.com/bluetoother/ble-shepherd/blob/master/lib/drivers/ccbnp_drivers.js#L98) API to confirm whether ble-shepherd has sent a connect request and see the connect results, please refer to the following code:

```js
ccbnpDrivers.connect = function (periph) {
    var deferred = Q.defer(),
        addrType;

    // add the following code
    console.log('-------------connect to peripheral-------------');
    console.log(periph.addr);

    addrType = periph.addrType;
    if (!_.isNumber(addrType))
        addrType = addrType === 'random' ? 0x01 : 0x00;

    this.cancelScan().then(function () {
        return ccbnp.gap.estLinkReq(1, 0, addrType, periph.addr);
    }, function () {
        return ccbnp.gap.estLinkReq(1, 0, addrType, periph.addr);
    }).done(function (result) {
        // add the following code
        console.log('----------------connect success----------------');
        console.log(result);

        var addr = result.collector.GapLinkEstablished[0].addr;

        if (addr === '0x000000000000')
            deferred.reject(new Error('Connect Timeout'));
        else 
            deferred.resolve(addr);
    }, function (err) {
        // add the following code
        console.log('-----------------connect error-----------------');
        console.log(err);

        if (err.message === 'bleNoResources') 
            deferred.reject(new Error('Connection Limit Exceeded'));
        else 
            deferred.reject(err);
    });

    return deferred.promise;
};
```

Thank you.

**Comment by amigomcu** [comment]
hi ,
this is my message with log,
that don't have any error.but i don't see link with central.

I will appreciate your help with this situation.

discoveredHdlr:
> var discoveredHdlr = function (peripheralInfo, callback) {
>     console.log('discover addr:'+peripheralInfo.addr);
>     if(	peripheralInfo.addr == 0xe6025660c82b ) {
> 	    console.log('try to connect');
> 	    setImmediate(function () {
>         	callback(null, true);
>     	});
>     }
>     else {
> 	    console.log('connect return');
> 	    setImmediate(function () {
>         	callback(null, false);
>     	});
>     }	
> };

log:
> [sudo] password for user: 
> discover addr:0xe6025660c82b
> try to connect
> -------------connect to peripheral-------------
> 0xe6025660c82b
> ----------------connect success----------------
> { status: 0,
>   opcode: 65033,
>   dataLen: 0,
>   payload: <Buffer >,
>   collector: { GapLinkEstablished: [ [Object] ] } }
> discover addr:0xe6025660c82b
> try to connect
> -------------connect to peripheral-------------
> 0xe6025660c82b
> ----------------connect success----------------
> { status: 0,
>   opcode: 65033,
>   dataLen: 0,
>   payload: <Buffer >,
>   collector: { GapLinkEstablished: [ [Object] ] } }
> discover addr:0xe6025660c82b
> try to connect
> discover addr:0xc86e23e02684
> connect return
> -------------connect to peripheral-------------
> 0xe6025660c82b
> ----------------connect success----------------
> { status: 0,
>   opcode: 65033,
>   dataLen: 0,
>   payload: <Buffer >,
>   collector: { GapLinkEstablished: [ [Object] ] } }
> discover addr:0xe6025660c82b
> try to connect
> -------------connect to peripheral-------------
> 0xe6025660c82b
> ----------------connect success----------------
> { status: 0,
>   opcode: 65033,
>   dataLen: 0,
>   payload: <Buffer >,
>   collector: { GapLinkEstablished: [ [Object] ] } }
> discover addr:0xe6025660c82b
> try to connect
> -------------connect to peripheral-------------
> 0xe6025660c82b
> ^Cuser@ubuntu:~/ble-shepherd/examples$

**Comment by hedywings** [comment]
Hi @amigomcu,

I think the device can not join the network is not associated with random address type, because I also have a nRF52 development kit, and I flash the ble_app_blinky to nRF52 with random address type, the test results is that it can join the network normally.

ble-shepherd@1.1.7

Here is my onDiscivered(0 handler:
```js
central.onDiscovered(function (peripheralInfo, callback) {
    console.log('discover addr:' + peripheralInfo.addr);
    console.log(peripheralInfo);

    if( peripheralInfo.addr === '0xfa928c949f56' ) {
        console.log('try to connect');
        setImmediate(function () {
            callback(null, true);
        });
    } else {
        console.log('connect return');
        setImmediate(function () {
            callback(null, false);
        });
    }
});
```

And I add some console.log() in `ind` event handler to see `devStatus` and `devIncoming` message:
```js
central.on('ind', function(msg) {
    var periph = msg.periph;

    switch (msg.type) {
        case 'devStatus':
            console.log('Peripheral ' + periph.addr + ' status changed to ' + msg.data);
            break;
        case 'devIncoming':
            console.log('Peripheral ' + periph.addr + ' incoming the network');
            //...
            break;
        //...
    }
});
```

Log message
```
discover addr:0xfa928c949f56
{ addr: '0xfa928c949f56',
  advertisement: 
   { flags: 6,
     localName: 'Nordic_Blinky',
     serviceUuids: [ '000015231212efde1523785feabcd123' ] } }
try to connect
discover addr:0x20c38ff19403
{ addr: '0x20c38ff19403',
  advertisement: 
   { flags: 6,
     localName: 'WeatherStation',
     connInterval: { min: 80, max: 80 },
     txPowerLevel: 0 } }
connect return
Peripheral 0xfa928c949f56 incoming the network
Peripheral 0xfa928c949f56 status changed to online
```

Could you please add one more console.log() in [ccbnpDrivers.connect](https://github.com/bluetoother/ble-shepherd/blob/master/lib/drivers/ccbnp_drivers.js#L98) to see the connection is successfully established or timeout.
```js
ccbnpDrivers.connect = function (periph) {
    var deferred = Q.defer(),
        addrType;

    addrType = periph.addrType;
    if (!_.isNumber(addrType))
        addrType = addrType === 'random' ? 0x01 : 0x00;

    this.cancelScan().then(function () {
        return ccbnp.gap.estLinkReq(1, 0, addrType, periph.addr);
    }, function () {
        return ccbnp.gap.estLinkReq(1, 0, addrType, periph.addr);
    }).done(function (result) {
        var addr = result.collector.GapLinkEstablished[0].addr;
        // add the following code
        console.log(result.collector.GapLinkEstablished);

        if (addr === '0x000000000000')
            deferred.reject(new Error('Connect Timeout'));
        else 
            deferred.resolve(addr);
    }, function (err) {
        if (err.message === 'bleNoResources') 
            deferred.reject(new Error('Connection Limit Exceeded'));
        else 
            deferred.reject(err);
    });

    return deferred.promise;
};
```

And you can also add some console.log() in `ind` event handler to see `devStatus` and `devIncoming` message, thank you!

**Comment by amigomcu** [comment]
hi hedywings ,
excause me, this is my issue.
i rebuild ble-shepherd project,now it is ok.
i will check my mistake later.

^Cuser@ubuntu:~/ble-shepherd/examples$ sudo node sensorTagApp.js 
-------------connect to peripheral-------------
0xe6025660c82b
----------------connect success----------------
{ status: 0,
  opcode: 65033,
  dataLen: 0,
  payload: <Buffer >,
  collector: { GapLinkEstablished: [ [Object] ] } }
[ { addr: '0xe6025660c82b',
    connHandle: 0,
    connRole: 8,
    connInterval: 24,
    connLatency: 0,
    connTimeout: 200,
    clockAccuracy: 0 } ]
-------------connect to peripheral-------------
0xfa928c949f56
-----------------connect error-----------------
[Error: GapEstLinkReq timeout.]
